---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"
  tags: 'data'

# set AD datas ==================================================================================================

- name: Prepare servers set admin password, set hostname
  hosts: domain
  roles:
  - { role: 'settings/admin_password', tags: 'admin_password' }
  - { role: 'settings/hostname', tags: 'hostname' }
  vars:
    local_admin_password: "{{lab.hosts[dict_key].local_admin_password}}"
    hostname: "{{lab.hosts[dict_key].hostname}}"


# parent controlers
- name: Main DC AD configuration
  hosts: parent_dc
  roles:
  - { role: 'domain_controller', tags: 'dc_main_domains' }
  vars:
    domain: "{{lab.hosts[dict_key].domain}}"
    domain_password: "{{lab.domains[domain].domain_password}}"
    netbios_name: "{{lab.domains[domain].netbios_name}}"

# child
- name: Child DC AD configuration
  hosts: child_dc
  roles:
    - { role: 'child_domain', tags: 'child_domain'}
  vars:
    domain: "{{lab.hosts[dict_key].domain}}"
    domain_password: "{{lab.domains[domain].domain_password}}"
    netbios_name: "{{lab.domains[domain].netbios_name}}"
    parent_domain: "{{'.'.join(domain.split('.')[1:])}}"
    parent_domain_password: "{{lab.domains[parent_domain].domain_password}}"
    source_dc: "{{lab.hosts[lab.domains[parent_domain].dc].hostname}}.{{parent_domain}}"

- name: "play servers AD configuration"
  hosts: server
  roles:
    - { role: 'member_server', tags: 'server'}
  vars:
    member_domain: "{{lab.hosts[dict_key].domain}}"
    domain_password: "{{lab.domains[member_domain].domain_password}}"

- name: "play workstations AD configuration"
  hosts: workstation
  roles:
    - { role: 'commonwkstn', tags: 'workstation'}
  vars:
    member_domain: "{{lab.hosts[dict_key].domain}}"
    domain_password: "{{lab.domains[member_domain].domain_password}}"