---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"
  tags: 'data'
# set AD datas ==================================================================================================

- name: ADCS
  hosts: adcs
  roles:
  - { role: 'adcs', tags: 'adcs'}
  vars:
    domain: "{{lab.hosts[dict_key].domain}}"
    domain_username: "{{domain}}\\Administrator"
    domain_password: "{{lab.domains[domain].domain_password}}"
    ca_common_name: "{{lab.domains[domain].netbios_name}}-CA"

- name: ADCS
  hosts: adcs_customtemplates
  roles:
  - { role: 'adcs_templates', tags: 'adcs_templates'}
  vars:
    domain: "{{lab.hosts[dict_key].domain}}"
    domain_username: "{{domain}}\\Administrator"
    domain_password: "{{lab.domains[domain].domain_password}}"
    ca_common_name: "{{lab.domains[domain].netbios_name}}-CA"
    ca_host: "{{lab.domains[domain].ca_server}}"


# Force certificate enrollment on DC
# certutil -addstore root \\braavos\CertEnroll\braavos.essos.local_ESSOS-CA.crt
# certutil -addstore CA \\braavos\CertEnroll\ESSOS-CA.crl
# certutil -addstore CA \\braavos\CertEnroll\ESSOS-CA+.crl
# and do gpupdate /force on dc03 and srv03