---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"
  tags: 'data'

- name: "Install IIS"
  hosts: iis
  roles:
    - { role: 'iis', tags: 'iis'}

- name: "Install MSSQL Express"
  hosts: mssql
  roles:
    - { role: 'mssql', tags: 'mssql'}
    - { role: 'mssql_link', tags: 'mssql, mssql_link'}
  vars:
    domain: "{{lab.hosts[dict_key].domain}}"
    SQLSVCACCOUNT_NAME: "{{lab.hosts[dict_key].mssql.svcaccount}}"
    SQLSVCACCOUNT: "{{domain}}\\{{SQLSVCACCOUNT_NAME}}"
    SQLSVCPASSWORD: "{{lab.domains[domain].users[SQLSVCACCOUNT_NAME].password}}"
    SQLYSADMIN: "{{SQLSVCACCOUNT}}"
    domain_admin: "{{domain}}\\Administrator"
    domain_admin_password: "{{lab.domains[domain].domain_password}}"
    sql_sysadmins: "{{lab.hosts[dict_key].mssql.sysadmins | default([]) }}"
    executeaslogin: "{{lab.hosts[dict_key].mssql.executeaslogin  | default({}) }}"
    executeasuser:  "{{lab.hosts[dict_key].mssql.executeasuser | default({}) }}"
    sa_password: "{{lab.hosts[dict_key].mssql.sa_password}}"
    linked_servers: "{{lab.hosts[dict_key].mssql.linked_servers | default({}) }}"

- name: "Install SQL Server Management Studio"
  hosts: mssql_ssms
  roles:
    - { role: 'mssql_ssms', tags: 'mssql_ssms'}

- name: "Install Webdav"
  hosts: webdav
  roles:
    - { role: 'webdav', tags: 'webdav'}